### PR TITLE
images in Ch 2 and 5, proofreading

### PR DESCRIPTION
**Pull request by lmichael107**

### CODE REVIEW

**Comment by ChristinaLK** [comment]
the CHPC brochures are doing wacky things when I look at the "files changed" tab.  Anyone else?

**Comment by lmichael107** [comment]
I ended up not using those particular images, and remaking images with only
one page. (GitHub seems to strangely toggle between pages for multi-page
images.)

Know of a way to remove files from a repo, directly in GitHub? (Otherwise,
I'll clone to my workstation, delete, and eventually update the pull
request.)

Lauren

Lauren Michael - Research Computing Facilitator, Center for High Throughput
Computing <http://chtc.cs.wisc.edu/>, University of Wisconsin - Madison
Other Affiliations: Advanced Computing Initiative
<http://aci.wisc.edu/>; Wisconsin
Institute for Discovery <http://wid.wisc.edu/profile/lauren-michael/>;
ACI-REF <http://aci-ref.org/>
lmichael@wisc.edu, www.tinyurl.com/LMichaelCalendar, Discovery 2262,
(608)316-4430

**Comment by ChristinaLK** [comment]
no. if there's a way to remove files, you can probably find it as quickly as I can.

**Comment by lmichael107** [comment]
Good point... :) I've removed those files and updated the pull request. (Apparently, there's a delete/trash-can icon near top-right of viewing each file, FYI. https://github.com/blog/1545-deleting-files-on-github)

**Comment by ChristinaLK** [comment]
this looks good to me.

**Pull request merged**
