### PR TITLE
Template and CSS changes, adding icons, and examples in the test chapter page

### PR DESCRIPTION
**Pull request by devbioinfoguy**

### CODE REVIEW

**Comment by lmichael107** [comment]
Hi Bob,

Lots of work! Given that there are a lot of chapters changed and that we can't follow our usual review process, perhaps you can at least confirm that you tested these changes, visually, in your own GitHub repo of the best practices doc?

**Comment by devbioinfoguy** [comment]
Yes, previews were done in the images/01-testing-images/ rendered doc in my fork of the repo. All OK there. Style sheet changes only affect elements using the new classes, so no chance of something existing being changed.

  I did catch one minor glitch: if chapters didn't have the keyword 'icon' with a filename defined in the YAMP, then a broken image placeholder appeared next to the chapter title. I made that icon code conditional in the _layout/chapter.html, so when the icon is put in, the chapter title will appear changed. Otherwise, it is unaltered.

  In total, only css/main.css and _layouts/chapter.html changed. Icon files added to images/, and images/01-testing-images.md changed. 

-Bob

**Comment by ChristinaLK** [comment]
This looks good to me.  Should I go ahead and merge?

**Comment by lmichael107** [comment]
yes! -L

Lauren Michael - Research Computing Facilitator, Center for High Throughput
Computing <http://chtc.cs.wisc.edu/>, University of Wisconsin - Madison
Other Affiliations: Advanced Computing Initiative
<http://aci.wisc.edu/>; Wisconsin
Institute for Discovery <http://wid.wisc.edu/profile/lauren-michael/>;
ACI-REF <http://aci-ref.org/>
lmichael@wisc.edu, www.tinyurl.com/LMichaelCalendar, Discovery 2262,
608.316.4430

**Pull request merged**
