### PR TITLE
Add images for Chap 7

### PR DESCRIPTION
**Pull request by shwina**
@devbioinfoguy (or anyone else!) I ran into the following rendering problem; could you please confirm if you see the same? I'm not sure how to fix:

rendering-issue

### CODE REVIEW

**Comment by devbioinfoguy** [comment]
Confirmed. I'll look at this Thursday morning. Might have to pull @scleveland  in on this, but I'll do so only after I've failed.

Do you see this at all page widths? 

We might be able to fix by setting the fill color of the div/box for the image to white.

-B

**Comment by shwina** [comment]
@devbioinfoguy Not all widths. If the width is small enough that the text on the left flows further down than the image, then it looks better:

better-rendering

**Comment by devbioinfoguy** [comment]
We might have to include a break or separator to ensure there is clean rendering between the two sections.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by devbioinfoguy** [comment]
w3schools suggests using a 'clear' style to help the listbox clear the float. I'll go ahead and merge your changes in and then fix locally.

-Bob

**Pull request merged**
