### PR TITLE
Adding direct link to open issue on github

### PR DESCRIPTION
**Pull request by scleveland**
Adding direct link to open issue on github

### CODE REVIEW

**Comment by scleveland** [comment]
We should have a direct link to making an issue in the best practices

**Comment by lmichael107** [comment]
Thanks! -Lauren

**Comment by lmichael107** [comment]
Hi Sean,

There is a conflict with your pull request, likely because you didn't first update your own copy of the gh-pages branch, before making changes. I'm working on trying to fix the conflict ...

**Comment by lmichael107** [comment]
Sean,
I contacted GitHub, as the "revert" button for this pull request doesn't appear at right like it should. The instructions for resolving via the command line also didn't work - they resulted in me trying to push directly to YOUR repository, which I don't have permissions to do. -Lauren

**Pull request closed without merging**
